global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'example.smtp.com:587'
  smtp_from: 'example@examle.com'
  smtp_auth_username: 'example@example.com'
  smtp_auth_password: 'example'

  store: 'github.db'

jobs:
- name: 'githubtrending'
  # run every 5 minute
  cron: '*|*/5'
  url:
    test_target: 'examples/githubtrending'
    target: 'https://github.com/trending/{lang}?since=daily'
    query_parameter:
      lang: 
        - type: string
          value: all
        - type: string
          value: go 
        - type: string
          value: python
        - type: string
          value: java 
        - type: string
          value: markdown
        - type: distinct
          value: lang
  parser: 'githubtrending'

parsers:
- name: 'githubtrending'
  base_url: 'https://github.com'
  base_xpath: 
  - "//article[@class='Box-row']"
  attr:
    url: 'h1/a/@href'
    repo: 'h1/a'
    desc: "p"
    lang: "div/span/span[@itemprop='programmingLanguage']"
    star: "div/a[1]"
    fork: "div/a[2]"
    today: "div/span[3]"
  format:
    markdown: '[{lang}: {repo}]({url}), star: {star}, fork: {fork}, today-star: {today} <br> {desc}' 
    html: '<p><a href="{url}">{lang}: {repo}</a> start: {star}, fork: {fork}, today-star: {today}, {desc}</p>'

receivers:
- name: 'example'
  email_configs:
    to: 
    - 'example@example.com'
